config/routes.rb
Rails.application.routes.draw do


  root to: 'admin/deliveries#index'   


  namespace :admin do
    resources :points
  end
  namespace :admin do
    resources :assistants
  end
  namespace :admin do
    resources :buys
  end
  devise_for :users


  #
  namespace :admin do

    root 'deliveries#index'

    resources :deliveries    
    resources :sellers  
    resources :products  
    resources :clients
    resources :invoices
    resources :trucks
    resources :reports 

    post '/trucks/set_qtd',            to: 'trucks#set_qtd'      
    post '/trucks/set_bottle',         to: 'trucks#set_bottle'        
    get  '/truck/clear_truck',         to: 'trucks#clear_truck'        

    get  '/buy/cancel_buy',            to: 'buys#cancel_buy'          

    get  '/delivery/cancel_delivery',  to: 'deliveries#cancel_delivery'          


  end  

  #
  namespace :api1 do

    # deliveries
    post '/deliveries/sign',          to: 'deliveries#sign'  
    post '/deliveries/save',          to: 'deliveries#save' 
    get  '/deliveries/get_by_seller', to: 'deliveries#get_by_seller'
    get  '/deliveries/delete',        to: 'deliveries#delete' 
    get  '/deliveries/confirm_paid',  to: 'deliveries#confirm_paid'    

    # invoices
    post '/invoices/save',         to: 'invoices#save'    
    get '/invoices/get_by_seller', to: 'invoices#get_by_seller'

    # products
    get '/products', to: 'products#index'

    # clients
    get  '/clients',           to: 'clients#index'
    post '/clients/add',           to: 'clients#add' 

    # assistants
    get  '/assistants',           to: 'assistants#index'

    # sellers
    post '/sellers/set_truck', to: 'sellers#set_truck'    
    post '/sellers/set_location', to: 'sellers#set_location'    

    # trucks  
    get '/trucks', to: 'trucks#index'          


  end



end

app/models/client.rb
class Client < ApplicationRecord


    has_many :client_product

    has_many :delivery

    after_create :create_client_products

    validates_uniqueness_of :nome, :message => " - Já existe um cliente com esse nome"

	attr_reader   :distance_s #getter
	attr_writer   :distance #setter

	def create_client_products
	  puts self.inspect
	end



	def distance_s
	  return self.distance
	end

	# attr_writer
	def distance=(val)
	  self.distance = 5
	end


	def distance_between=(lat1, lon1, lat2, lon2)

		rad_per_deg = Math::PI / 180
		rm = 6371000 # Earth radius in meters


		lat1_rad, lat2_rad = lat1 * rad_per_deg, lat2 * rad_per_deg  
        lon1_rad, lon2_rad = lon1 * rad_per_deg, lon2 * rad_per_deg

	    a = Math.sin((lat2_rad - lat1_rad) / 2) ** 2 + Math.cos(lat1_rad) * 
	        Math.cos(lat2_rad) * Math.sin((lon2_rad - lon1_rad) / 2) ** 2  

	    c = 2 * Math::atan2(Math::sqrt(a), Math::sqrt(1 - a))

	    rm * c

	end



end

app/controllers/admin/clients_controller.rb
class Admin::ClientsController < Admin::ApplicationController
  

  before_action :set_admin_client, only: [:show, :edit, :update, :destroy]

  before_action :set_admin_products



  def index

    @admin_clients = Client.all 

    if params[:q]

      @admin_clients = Client
        .where( [ "clients.nome LIKE ?", "%#{params[:q]}%"  ] )
        .or( 
          Client.where( [ "clients.telefone LIKE ?", "%#{params[:q]}%"  ] ) 
        )
        .or( 
          Client.where( [ "clients.endereco LIKE ?", "%#{params[:q]}%"  ] ) 
        )
        .or( 
          Client.where( [ "clients.obs LIKE ?", "%#{params[:q]}%"  ] ) 
        )  
      
    end   


    @admin_clients      = @admin_clients.paginate( :page => params[:page] ) 
    

  end



  def show
  end


  def new
    @admin_client = Client.new
  end


  def edit  
  end


  def create

    @admin_client = Client.new(admin_client_params)


    if @admin_client.save

      params[:product].each do |product_id, preco|

        client_product = ClientProduct.new

        client_product.client_id  = @admin_client.id  
        client_product.product_id = product_id.to_i
        client_product.preco      = preco.to_f

        client_product.save  

      end

      flash[:success] = "Salvo com sucesso!"  

      redirect_to :controller => 'clients', :action => 'index'

    else

      render :new

    end 

    params.inspect

  end  


  def update

    respond_to do |format|

      if @admin_client.update(admin_client_params)

        params[:product].each do |product_id, preco|

          client_product = ClientProduct
            .where( [ "client_products.client_id = ?", @admin_client.id ] )
            .where( [ "client_products.product_id = ?", product_id.to_i ] )
            .first

          client_product.preco      = preco.to_f  

          client_product.save    

        end

        format.html { redirect_to [ :admin,  @admin_client], notice: 'Salvo com sucesso.' }

      else

        format.html { render :edit }

      end  
    end

  end


  def destroy

    @admin_client.destroy

    respond_to do |format|
      format.html { redirect_to admin_clients_url, notice: 'Excluido.' }
      format.json { head :no_content }
    end

  end

  private


    def set_admin_client
      @admin_client = Client.find(params[:id])
    end    


    def set_admin_products
      @admin_products = Product.all
    end

    def admin_client_params
      params.require(:client).permit(:nome, :tipo_preco, :telefone, :latitude, :longitude, :endereco, :obs)
    end


end

app/controllers/api1/clients_controller.rb
class Api1::ClientsController < ApplicationController

    skip_before_action :verify_authenticity_token


	def index_

		@clients = Client
			.find_by_sql(
				"SELECT * FROM (SELECT *,(((acos(sin((" + params[:latitude] + "*pi()/180)) * 
				sin((latitude*pi()/180))+cos((" + params[:latitude] + "*pi()/180)) * 
				cos((latitude*pi()/180)) * cos((( " + params[:longitude] + " - longitude)* 
				pi()/180))))*180/pi())*60*1.1515 ) as distance 
				FROM clients WHERE 1 GROUP BY ID) as X 
				ORDER BY distance, nome ASC"  
           )     


	end


	def index

		@clients = Client.all.order(nome: :asc) 

	end


	def add

		@client  = Client.new

		@client.latitude    = params[:latitude]
		@client.longitude   = params[:longitude]
		@client.nome        = params[:nome]
		@client.tipo_preco  = params[:tipo_preco] 

		@client.save

	end


end

app/views/admin/clients/_form.html.erb
<%= form_for([ :admin,  @admin_client], html: { class: "form-horizontal", role: "form" }) do |f| %>

  <% if @admin_client.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">

      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span><span class="sr-only">
          Fechar
        </span>
      </button>

      <h4><%= @admin_client.errors.count %> erro(s) ao salvar:</h4>

      <ul>
      <% @admin_client.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>  
      <% end %>
      </ul>

    </div>
    
  <% end %>


  <div class="form-group">

    <div class="col-sm-4 col-xs-12" >

      <%= f.label :nome %>

      <div>
        <%= f.text_field :nome, class: "form-control", :required => true %>
      </div> 

    </div>

    <div class="col-sm-4 col-xs-12" >

      <%= f.label :telefone %>
     
      <div>
        <%= f.text_field :telefone, class: "form-control", :required => true %>
      </div>  

    </div>

  </div>


 <div class="form-group" >
      
    <fieldset>

      <legend class="col-xs-12" >
        Preços para cliente
      </legend>

  
      <% if @admin_client.client_product.count == 0 %>

        <% @admin_products.each do |product| %>

              <div class="col-xs-12 col-sm-4">

                <label for="client_nome">
                  <%= product.nome %>  
                </label>

                <div>
                  <input 
                    class="form-control money col-xs-12"     
                    required="required"   
                    value="<%= number_with_precision( product.preco_base, :precision => 2) %>" 
                    name="product[<%= product.id %>]" >  
                </div> 

              </div>

        <% end %>

      <% end %>


      <% if @admin_client.client_product.count > 0 %>

        <% @admin_client.client_product.each do |product| %>

              <div class="col-xs-12 col-sm-4">

                <label for="client_nome">
                  <%= product.product.nome %>  
                </label>

                <div>
                  <input 
                    class="form-control money col-xs-12"   
                    required="required"   
                    value="<%= number_with_precision( product.preco, :precision => 2) %>" 
                    name="product[<%= product.product.id %>]" >  
                </div> 

              </div>

        <% end %>

      <% end %>



    </fieldset>

  </div>


  <div class="form-groupp hide ">

    <div class="col-sm-6">

      <%= f.label :latitude %>

      <div>
        <%= f.text_field :latitude, class: "form-control", disabled: "disabled" %>
      </div>

    </div>

    <div class="col-sm-6">

      <%= f.label :longitude %> 
      <div>
        <%= f.text_field :longitude, class: "form-control", disabled: "disabled" %>
      </div>

    </div>

  </div>


  <div class="col-xs-12" >
  </div>  


  <div class="form-group">
    

    <div class="col-sm-6">

      <%= f.label :endereco %>

      <div>
        <%= f.text_area :endereco, class: "form-control", :required => true %>
      </div> 

      <div style="display: none" id="client_sugest_container" >

        <h6>Sugestão</h6>

        <div id="client_sugest" >    
          
        </div>  


        <div >  
          <a href="javascript: $('#client_endereco').val(  $('#client_sugest').html() ); ">
            Aceitar sugestão
          </a>
        </div>      
        
      </div>

      
    </div>


    <div class="col-sm-6">

      <%= f.label :obs %>

      <div>
        <%= f.text_area :obs, class: "form-control" %>
      </div>

    </div>


  </div>



  <div class="form-group">

    <div class=col-sm-12">

      <%= f.submit "Cadastrar cliente", class: "btn btn-primary col-xs-12" %>

    </div>

  </div>


<% end %>


<div class="col-sm-12" > 
    <div style="width: 100%; height: 480px" id="mapContainer"></div>
</div>

app/views/admin/clients/edit.html.erb
<div class="page-header">

  <a class="btn btn-default" href="javascript: window.history.back();">
    <span class="glyphicon glyphicon-list-alt"></span>
    Voltar
  </a>

  <h1>Editar cliente</h1>
  
</div>

<%= render 'form' %>

app/views/admin/clients/index.html.erb
<div class="page-header">
  <%= link_to new_admin_client_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
  <% end %>

  <h1>
    Clientes cadastrados
  </h1> 

  <%= render '/admin/general/search_form' %> 


</div>


<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th class="col-xs-1">Código</th>
            <th class="col-xs-4" >Nome</th>
            <th class="hidden-xs" >Telefone</th>
            <th class="hidden-xs col-xs-4">Endereco</th>

            <th class="col-xs-1" ></th>
      </tr>
    </thead>

    <tbody>

      <% @admin_clients.each do |admin_client| %>

        <tr>



            <td><%= admin_client.id %></td>
            <td><%= admin_client.nome %></td>
            <td class="hidden-xs" ><%= admin_client.telefone %></td>
            <td class="hidden-xs col-xs-4"><%= admin_client.endereco %></td>

            <td class="text-center" >
                <% link_to '', admin_client_path(admin_client), class: "btn btn-default glyphicon glyphicon glyphicon-ok" %>
                <%= link_to '', edit_admin_client_path(admin_client), class: "btn btn-default glyphicon glyphicon-cog" %>
                <% link_to '', [:admin, admin_client], method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger glyphicon glyphicon-remove"%>
            </td>

        </tr>


      <% end %>


    </tbody>
  </table>
</div>


<div class="col-xs-12" >
    <%= will_paginate @admin_clients, 
        :previous_label => t("← Anterior"), 
        :next_label => t("Próximo →"),
        renderer: BootstrapPagination::Rails %>
</div>

app/views/admin/clients/new.html.erb
<div class="page-header">
  <%= link_to admin_clients_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Voltar
  <% end %>
  <h1>
  	Cadastrar cliente
  </h1>
</div>

<%= render 'form' %>

app/views/admin/clients/show.html.erb
<div class="page-header">

  <a class="btn btn-default" href="javascript: window.history.back();">
    <span class="glyphicon glyphicon-list-alt"></span>
    Voltar
  </a>
  
  <h1>
    Cliente
  </h1>
</div>

<dl class="dl-horizontal">
  <dt>Nome:</dt>
  <dd><%= @admin_client.nome %></dd>

  <dt>Telefone:</dt>
  <dd><%= @admin_client.telefone %></dd>


  <dt>Endereco:</dt>
  <dd><%= @admin_client.endereco %></dd>

  <dt>Obs:</dt>
  <dd><%= @admin_client.obs %></dd>   

</dl>


<div class="hidden" style="width: 100%; height: 480px" id="mapContainer"></div>


<script>

    // Initialize the platform object:
    var platform = new H.service.Platform({
        'app_id': 'xLCFXVMRONHZDZ1BCcds',
        'app_code': 'et-o6Pb5bNjJxObiALOTpA'
    });

    // Obtain the default map types from the platform object
    var maptypes = platform.createDefaultLayers();

    // Instantiate (and display) a map object:
    var map = new H.Map(
        document.getElementById('mapContainer'),
        maptypes.normal.map,   
        {
            zoom: 16,
            center: { 
                lng: <%= @admin_client.longitude %>, 
                lat: <%= @admin_client.latitude %>
            }
        }
    );




    // Create an icon, an object holding the latitude and longitude, and a marker:

      coords = {   
                lng: <%= @admin_client.longitude %>, 
                lat: <%= @admin_client.latitude %>
            },


      marker = new H.map.Marker(coords);  

    // Add the marker to the map and center the map at the location of the marker:
    map.addObject(marker);


</script>