config/routes.rb
Rails.application.routes.draw do


  root to: 'admin/deliveries#index'   


  namespace :admin do
    resources :points
  end
  namespace :admin do
    resources :assistants
  end
  namespace :admin do
    resources :buys
  end
  devise_for :users


  #
  namespace :admin do

    root 'deliveries#index'

    resources :deliveries    
    resources :sellers  
    resources :products  
    resources :clients
    resources :invoices
    resources :trucks
    resources :reports 

    post '/trucks/set_qtd',            to: 'trucks#set_qtd'      
    post '/trucks/set_bottle',         to: 'trucks#set_bottle'        
    get  '/truck/clear_truck',         to: 'trucks#clear_truck'        

    get  '/buy/cancel_buy',            to: 'buys#cancel_buy'          

    get  '/delivery/cancel_delivery',  to: 'deliveries#cancel_delivery'          


  end  

  #
  namespace :api1 do

    # deliveries
    post '/deliveries/sign',          to: 'deliveries#sign'  
    post '/deliveries/save',          to: 'deliveries#save' 
    get  '/deliveries/get_by_seller', to: 'deliveries#get_by_seller'
    get  '/deliveries/delete',        to: 'deliveries#delete' 
    get  '/deliveries/confirm_paid',  to: 'deliveries#confirm_paid'    

    # invoices
    post '/invoices/save',         to: 'invoices#save'    
    get '/invoices/get_by_seller', to: 'invoices#get_by_seller'

    # products
    get '/products', to: 'products#index'

    # clients
    get  '/clients',           to: 'clients#index'
    post '/clients/add',           to: 'clients#add' 

    # assistants
    get  '/assistants',           to: 'assistants#index'

    # sellers
    post '/sellers/set_truck', to: 'sellers#set_truck'    
    post '/sellers/set_location', to: 'sellers#set_location'    

    # trucks  
    get '/trucks', to: 'trucks#index'          


  end



end

app/models/assistant.rb
class Assistant < ApplicationRecord
end

app/controllers/admin/assistants_controller.rb
class Admin::AssistantsController < Admin::ApplicationController
  before_action :set_admin_assistant, only: [:show, :edit, :update, :destroy]



  def index
    @admin_assistants = Assistant.all
  end


  def show
  end


  def new
    @admin_assistant = Assistant.new
  end


  def edit
  end


  def create
    @admin_assistant = Assistant.new(admin_assistant_params)

      if @admin_assistant.save

        flash[:success] = "Salvo com sucesso!"

        redirect_to :controller => 'assistants', :action => 'index'

      else  

        render :new

      end  

  end


  def update
    respond_to do |format|
      if @admin_assistant.update(admin_assistant_params)

        format.html { redirect_to admin_assistants_url, notice: 'Excluido.' }  

      else
        format.html { render :edit }
      end
    end
  end


  def destroy
    @admin_assistant.destroy
    respond_to do |format|
      format.html { redirect_to admin_assistants_url, notice: 'Excluido.' }
      format.json { head :no_content }
    end
  end

  private


    def set_admin_assistant
      @admin_assistant = Assistant.find(params[:id])
    end


    def admin_assistant_params
      params.require(:assistant).permit( :nome, :telefone, :doc, :pagamento_diaria )
    end


end

app/controllers/api1/assistants_controller.rb
class Api1::AssistantsController < ApplicationController

    skip_before_action :verify_authenticity_token


	def index

		@assistants = Assistant.all.order(nome: :asc) 

	end


end

app/views/admin/assistants/_form.html.erb
<%= form_for([ :admin,  @admin_assistant], html: { class: "form-horizontal", role: "form" }) do |f| %>


  <% if @admin_assistant.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@admin_assistant.errors.count, "error") %> prohibited this admin_assistant from being saved:</h4>

      <ul>
      <% @admin_assistant.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>



  <div class="form-group">
 
    <div class="col-sm-6" >  

        <%= f.label "Nome do ajudante", class: "" %>
        
        <div>
            <%= 
                f.text_field :nome,     
                class: "form-control",
                :required => true, 
                :placeholder => 'Digite o nome'
            %>
        </div>
        
    </div>

  </div>


  <div class="form-group">
 
    <div class="col-sm-6" >  

        <%= f.label "Telefone", class: "" %>
        
        <div>
            <%= 
                f.text_field :telefone,     
                class: "form-control",
                :required => true, 
                :placeholder => 'Digite o telefone'
            %>
        </div>
        
    </div>

  </div>


  <div class="form-group">
 
    <div class="col-sm-3" >  

        <%= f.label "Valor diária", class: "" %>
        
        <div>
            <%= 
                f.text_field :pagamento_diaria,     
                class: "form-control money",
                :value =>  number_with_precision( @admin_assistant.pagamento_diaria, :precision => 2 ) ,   
                :required => true, 
                :placeholder => '0.00' 
            %>
        </div>
        
    </div>

  </div>



  <div class="form-group">
 
    <div class="col-sm-3" >  

        <%= f.label "RG ou CPF", class: "" %>
        
        <div>
            <%= 
                f.text_field :doc,     
                class: "form-control ",
                :required => true, 
                :placeholder => 'Documento'  
            %>
        </div>
        
    </div>

  </div>


  <div class="form-group">
    <div class="col-xs-12">
      <%= f.submit "Salvar", class: "btn btn-primary col-xs-12" %>
    </div>
  </div>

<% end %>

app/views/admin/assistants/edit.html.erb
<div class="page-header">

	<a class="btn btn-default" href="javascript: window.history.back();">
	    <span class="glyphicon glyphicon-list-alt"></span>
	    Voltar
	</a>

 
  <h1>
  	Editar ajudante
  </h1>
  
</div>

<%= render 'form' %>

app/views/admin/assistants/index.html.erb
<div class="page-header">
  <%= link_to new_admin_assistant_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
  <% end %>
  <h1>
    Ajudantes
  </h1>
</div>



<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th class="col-xs-1" >Código</th>
            <th>Nome</th>
            <th>Telefone</th>
            <th>Documento</th>
            <th></th>
      </tr>
    </thead>

    <tbody>
      <% @admin_assistants.each do |admin_assistant| %>
      <tr>
        <td><%= admin_assistant.id %></td>
        <td><%= admin_assistant.nome %></td>
        <td><%= admin_assistant.telefone %></td>
        <td><%= cpf_rg( admin_assistant.doc ) %></td>  

        <td>  
          <%= link_to '', edit_admin_assistant_path(admin_assistant ), class: "btn btn-default glyphicon glyphicon-cog" %>
        </td>

      </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/admin/assistants/new.html.erb
<div class="page-header">

	<a class="btn btn-default" href="javascript: window.history.back();">
	    <span class="glyphicon glyphicon-list-alt"></span>
	    Voltar
	</a>


  <h1>Salvar ajudante</h1>
</div>

<%= render 'form' %>

app/views/admin/assistants/show.html.erb
<div class="page-header">
  <%= link_to admin_assistants_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_admin_assistant_path(@admin_assistant), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show admin_assistant</h1>
</div>

<dl class="dl-horizontal">
  <dt>Nome:</dt>
  <dd><%= @admin_assistant.nome %></dd>

  <dt>Telefone:</dt>
  <dd><%= @admin_assistant.telefone %></dd>

  <dt>Doc:</dt>
  <dd><%= @admin_assistant.doc %></dd>

</dl>