config/routes.rb
Rails.application.routes.draw do


  root to: 'admin/deliveries#index'   


  namespace :admin do
    resources :points
  end
  namespace :admin do
    resources :assistants
  end
  namespace :admin do
    resources :buys
  end
  devise_for :users


  #
  namespace :admin do

    root 'deliveries#index'

    resources :deliveries    
    resources :sellers  
    resources :products  
    resources :clients
    resources :invoices
    resources :trucks
    resources :reports 

    post '/trucks/set_qtd',            to: 'trucks#set_qtd'      
    post '/trucks/set_bottle',         to: 'trucks#set_bottle'        
    get  '/truck/clear_truck',         to: 'trucks#clear_truck'        

    get  '/buy/cancel_buy',            to: 'buys#cancel_buy'          

    get  '/delivery/cancel_delivery',  to: 'deliveries#cancel_delivery'          


  end  

  #
  namespace :api1 do

    # deliveries
    post '/deliveries/sign',          to: 'deliveries#sign'  
    post '/deliveries/save',          to: 'deliveries#save' 
    get  '/deliveries/get_by_seller', to: 'deliveries#get_by_seller'
    get  '/deliveries/delete',        to: 'deliveries#delete' 
    get  '/deliveries/confirm_paid',  to: 'deliveries#confirm_paid'    

    # invoices
    post '/invoices/save',         to: 'invoices#save'    
    get '/invoices/get_by_seller', to: 'invoices#get_by_seller'

    # products
    get '/products', to: 'products#index'

    # clients
    get  '/clients',           to: 'clients#index'
    post '/clients/add',           to: 'clients#add' 

    # assistants
    get  '/assistants',           to: 'assistants#index'

    # sellers
    post '/sellers/set_truck', to: 'sellers#set_truck'    
    post '/sellers/set_location', to: 'sellers#set_location'    

    # trucks  
    get '/trucks', to: 'trucks#index'          


  end



end

app/models/product.rb
class Product < ApplicationRecord

  belongs_to :brand

  after_create :create_truck_prducts


  def create_truck_prducts

  	puts self.inspect ;

  	@trucks = Truck.all

  	@trucks.each do |truck|

  		@truck_product = TruckProduct.new

  		@truck_product.truck_id         	= truck.id
  		@truck_product.product_id       	= self.id
  		@truck_product.quantidade_fonte   	= 0
  		@truck_product.quantidade_caminhao 	= 0

  		@truck_product.save

  	end

  end

end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < Admin::ApplicationController
  
  before_action :set_admin_product, only: [:show, :edit, :update, :destroy]

  before_action :set_admin_brands

  before_action :set_admin_sellers


  def index
    @admin_products = Product.all
  end


  def show
  end


  def new
    @admin_product = Product.new
  end


  def edit
  end


  def create

    @admin_product = Product.new(admin_product_params)


    if @admin_product.save

      # adicionar esse produto
      @clients = Client.all

      @clients.each do |client|

        client_product = ClientProduct.new

        client_product.client_id  = client.id
        client_product.product_id = @admin_product.id   
        client_product.product_id = @admin_product.id     

        client_product.save

      end

      flash[:success] = "Salvo com sucesso!"

      redirect_to :controller => 'products', :action => 'index'

    else
      render :new
    end

  end


  def update

      if @admin_product.update(admin_product_params)

        # salva os vendedores desse produto
        ProductSeller
          .where(:product_id => @admin_product.id)
          .destroy_all


        if params[:seller_id]  
          params[:seller_id].each do |seller_id|

            product_seller = ProductSeller.new
            product_seller.product_id = @admin_product.id
            product_seller.seller_id  = seller_id 
            product_seller.save  

          end  
        end  

        # Confirma e redireciona  
        flash[:success] = "Salvo com sucesso!"
        redirect_to :controller => 'products', :action => 'index'

      else
        render :edit
      end

  end


  def destroy
    #@admin_product.destroy
    #respond_to do |format|
    #  format.html { redirect_to admin_products_url, notice: 'Excluido com sucesso.' }
    #  format.json { head :no_content }
    #end
  end


  private

    def set_admin_product
      @admin_product = Product.find(params[:id])
    end

    def admin_product_params
      params.require(:product).permit(
        :nome, 
        :obs,  
        :preco_base,   
        :preco_compra_1,   
        :preco_compra_2,     
        :preco_venda_1,  
        :preco_venda_2,  
        :brand_id,     
      )
    end
 
    def set_admin_brands
      @admin_brands = Brand.all 
    end

    def set_admin_sellers
      @admin_sellers = Seller.all 
    end


end

app/controllers/api1/products_controller.rb
class Api1::ProductsController < ApplicationController

	def index
		@products = Product.all
	end


end

app/views/admin/products/_form.html.erb
<%= form_for([:admin, @admin_product], html: { class: "form-horizontal", role: "form" }) do |f| %>

    <% if @admin_product.errors.any? %>

        <div class="alert alert-danger alert-dismissable" role="alert">
            <button type="button" class="close" data-dismiss="alert">
                <span aria-hidden="true">&times;</span>
                <span class="sr-only">Close</span>
            </button>
            <h4>
                <%= pluralize(@admin_product.errors.count, "error") %> ao salvar:
            </h4>
            <ul>
                <% @admin_product.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
            </ul>
        </div>

    <% end %>



    <div class="form-group">

        <div class="col-sm-8 col-xs-12" >
            <%= f.label :nome, class: "" %>
            <div>
                <%= f.text_field :nome, class: "form-control", :required => true %>
            </div>
        </div>

        <div class="col-sm-4 col-xs-12">

            <label for="ex1">Marca</label>

            <select class="form-control" id="" name="product[brand_id]" placeholder="Código Cupom">   

                <% @admin_brands.each do |admin_brand| %>
                    <option

                        value="<%= admin_brand.id %>"

                        <% if admin_brand.id == @admin_product.brand_id %>  
                            selected
                        <% end %>                    

                    > 

                        <%= admin_brand.nome %>     

                    </option>
                <% end %>

                
            </select> 

        </div>  

        <div class="col-xs-12">
            <hr class="invisible" />
        </div>


        <div class="col-sm-3 col-xs-12" >  

            <%= f.label "Preço de compra", class: "" %>
            
            <div>
                <%= 
                    f.text_field :preco_compra_1,  
                    :required => true, 
                    :placeholder => '0.00',
                    :value => number_to_currency( @admin_product.preco_compra_1 ), 
                    class: "form-control money" 
                %>
            </div>
            
        </div>

        <div class="col-sm-3 col-xs-12" >  

            <%= f.label "Preço de compra(desconto)", class: "" %>
            
            <div>
                <%= 
                    f.text_field :preco_compra_2, 
                    class: "form-control money", 
                    :value => number_to_currency( @admin_product.preco_compra_2 ), 
                    :required => true,   
                    :placeholder => '0.00'   
                %>
            </div>
            
        </div>


    </div>

    <div class="form-group hide">

        <div class="col-sm-3 col-xs-12" >  

            <%= f.label "Preço médio", class: "" %>
            
            <div>
                <%= 
                    f.text_field :preco_base,     
                    class: "form-control money",
                    :value => number_to_currency( @admin_product.preco_base ), 
                    :required => true, 
                    :placeholder => '0.00',
                    :value => '0.00'
                %>
            </div>
            
        </div>

    </div>

    <div class="form-group" >
       
        <fieldset class="col-xs-12">

            <legend class="scheduler-border">Vendedores para o produto</legend>

        </fieldset>

        <% @admin_sellers.each do |seller| %>
        <div class="col-xs-12 col-sm-4" >

            <div class="checkbox">  

                <%  

                    checked = ""

                    seller.product_seller.each do |s|

                        if s.product_id == @admin_product.id
                            checked = "checked"
                        end
                    end

                %>

                <label>
                    <input type="checkbox" <%= checked %> name="seller_id[]"  value="<%= seller.id %>">
                    <%= seller.nome %>    
                </label>
            </div>      

        </div>  
        <% end %> 

    </div>




    <div class="form-group">

        <fieldset >
            
            <div class="col-xs-12 col-xs-12" >
                <legend></legend>
            </div>

            <div class="col-xs-12 col-xs-12" >

                <%= f.label :descricao, class: "" %>

                <div class="">
                    <%= f.text_area :obs, class: "form-control" %>
                </div>            

            </div>            

        </fieldset>

    </div>



    <div class="form-group">
        <div>
            <%= f.submit "Salvar", class: "btn btn-primary col-xs-12" %>
        </div>
    </div>


<% end %>

app/views/admin/products/edit.html.erb
<div class="page-header">

      <a class="btn btn-default" href="javascript: window.history.back();">
        <span class="glyphicon glyphicon-list-alt"></span>
        Voltar
      </a>

    <h1>
    	Editar produto
    </h1>
    
</div>

<%= render 'form' %>

app/views/admin/products/index.html.erb
<div class="page-header">
  <%= link_to new_admin_product_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
  <% end %>
  <h1>Produtos cadastrados</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
        <th class="col-xs-1">Código</th>
        <th>Nome</th>
        <th>Marca</th>
        <th>Anotações</th>
        <th class="col-xs-2" ></th>
      </tr>
    </thead>

    <tbody>
      <% @admin_products.each do |admin_product| %>  
        <tr>
          <td><%= admin_product.id %></td>
          <td><%= admin_product.nome %></td>
          <td><%= admin_product.brand.nome %></td>  
          <td><%= admin_product.obs %></td>  

            <td class="text-center" >
                <% link_to '', admin_product_path(admin_product), class: "btn btn-default glyphicon glyphicon glyphicon-ok" %>
                <%= link_to '', edit_admin_product_path(admin_product), class: "btn btn-default glyphicon glyphicon-cog" %>
                <% link_to '', 
                    [:admin, admin_product], 
                    method: :delete, data: { confirm: 'Tem certeza?' },   
                    class: "btn btn-danger glyphicon glyphicon-remove"%>
            </td>

        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/admin/products/new.html.erb
<div class="page-header">
  <%= link_to admin_products_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Voltar
  <% end %>
  <h1>Cadastrar produto</h1>
</div>

<%= render 'form' %>

app/views/admin/products/show.html.erb
<div class="page-header">
  <%= link_to admin_products_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Voltar
  <% end %>
  <%= link_to edit_admin_product_path(@admin_product), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Editar
  <% end %>
  <h1>
   Produto
  </h1>
</div>

<dl class="dl-horizontal">
  <dt>Nome:</dt>
  <dd><%= @admin_product.nome %></dd>

  <dt>Marca:</dt>
  <dd><%= @admin_product.brand.nome %></dd>

  <dt>Descricao:</dt>
  <dd><%= @admin_product.obs   %></dd>

  <dt>Preco:</dt>
  <dd><%= @admin_product.preco %></dd>

</dl>