config/routes.rb
Rails.application.routes.draw do


  root to: 'admin/deliveries#index'   


  namespace :admin do
    resources :points
  end
  namespace :admin do
    resources :assistants
  end
  namespace :admin do
    resources :buys
  end
  devise_for :users


  #
  namespace :admin do

    root 'deliveries#index'

    resources :deliveries    
    resources :sellers  
    resources :products  
    resources :clients
    resources :invoices
    resources :trucks
    resources :reports 

    post '/trucks/set_qtd',            to: 'trucks#set_qtd'      
    post '/trucks/set_bottle',         to: 'trucks#set_bottle'        
    get  '/truck/clear_truck',         to: 'trucks#clear_truck'        

    get  '/buy/cancel_buy',            to: 'buys#cancel_buy'          

    get  '/delivery/cancel_delivery',  to: 'deliveries#cancel_delivery'          


  end  

  #
  namespace :api1 do

    # deliveries
    post '/deliveries/sign',          to: 'deliveries#sign'  
    post '/deliveries/save',          to: 'deliveries#save' 
    get  '/deliveries/get_by_seller', to: 'deliveries#get_by_seller'
    get  '/deliveries/delete',        to: 'deliveries#delete' 
    get  '/deliveries/confirm_paid',  to: 'deliveries#confirm_paid'    

    # invoices
    post '/invoices/save',         to: 'invoices#save'    
    get '/invoices/get_by_seller', to: 'invoices#get_by_seller'

    # products
    get '/products', to: 'products#index'

    # clients
    get  '/clients',           to: 'clients#index'
    post '/clients/add',           to: 'clients#add' 

    # assistants
    get  '/assistants',           to: 'assistants#index'

    # sellers
    post '/sellers/set_truck', to: 'sellers#set_truck'    
    post '/sellers/set_location', to: 'sellers#set_location'    

    # trucks  
    get '/trucks', to: 'trucks#index'          


  end



end

app/models/buy.rb
class Buy < ApplicationRecord

  belongs_to :truck
  belongs_to :seller
  belongs_to :product 


  def destroy_complete  
    
  	truck_product = TruckProduct
        .where( [ "truck_products.truck_id     = ?", self.truck_id] )    
        .where( [ "truck_products.product_id   = ?", self.product_id] ) 
        .first  

    truck_product.quantidade_fonte    -=  self.quantidade
    truck_product.quantidade_caminhao -=  self.quantidade  

    if truck_product.save

      self.destroy
          
    end    

  end



end

app/controllers/admin/buys_controller.rb
class Admin::BuysController < Admin::ApplicationController

  before_action :set_admin_buy, only: [:show, :edit, :update]  

  before_action :set_admin_sellers, only: [:index]

  before_action :set_admin_clients, only: [:index]

  before_action :set_admin_products, only: [:index]

  before_action :set_admin_trucks, only: [:index]

  before_action :set_admin_brands, only: [:index]


  def index


    @data_inicial = Time.now.strftime("%Y-%m-%d")  
    @data_final   = Time.now.strftime("%Y-%m-%d")     

      
    if params[:data_inicial]
      @data_inicial = params[:data_inicial].to_datetime.strftime("%Y-%m-%d")  
    end

    if params[:data_final]
      @data_final   = params[:data_final].to_datetime.strftime("%Y-%m-%d")  
    end  

    @admin_buys = Buy
        .where( [ "buys.created_at   > ?", @data_inicial + " 00:00:00"] )    
        .where( [ "buys.created_at   < ?", @data_final + " 23:59:59"] ) 
        .order('id DESC') 


    if params[:seller_id] != '0'  
      @admin_buys =  @admin_buys.where( [ "buys.seller_id = ?", params[:seller_id] ] )
    end

    if params[:truck_id] != '0'  
      @admin_buys = @admin_buys.where( [ "buys.truck_id = ?", params[:truck_id] ] )
    end

    if params[:product_id] != '0'  
      @admin_buys = @admin_buys.where( [ "buys.product_id = ?", params[:product_id] ] )
    end 

    if params[:brand_id] != '0'  
      @admin_buys = @admin_buys
          .joins(:product)  
          .where( [ "products.brand_id = ?", params[:brand_id] ] )  
    end 

    # Compras geral
    @soma_buys = @admin_buys.sum( :valor ) 

    # Compras geral
    @soma_qtd = @admin_buys.sum( :quantidade ) 


  end


  def show
  end


  def new
    @admin_buy = Buy.new
  end


  def edit
  end


  def create

    @admin_buy = Buy.new(admin_buy_params)

    respond_to do |format|
      if @admin_buy.save
        format.html { redirect_to @admin_buy, notice: 'Buy was successfully created.' }
        format.json { render :show, status: :created, location: @admin_buy }
      else
        format.html { render :new }
        format.json { render json: @admin_buy.errors, status: :unprocessable_entity }
      end
    end
  end


  def update
    respond_to do |format|
      if @admin_buy.update(admin_buy_params)
        format.html { redirect_to @admin_buy, notice: 'Buy was successfully updated.' }
        format.json { render :show, status: :ok, location: @admin_buy }
      else
        format.html { render :edit }
        format.json { render json: @admin_buy.errors, status: :unprocessable_entity }
      end
    end
  end


  def cancel_buy

    @admin_buy = Buy.find( params[:buy_id] )    
    

    @admin_buy.destroy_complete


    respond_to do |format|
      format.html { redirect_to admin_buys_url, notice: 'Compra cancelada.' }  
    end    
    

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_buy
      @admin_buy = Admin::Buy.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def admin_buy_params
      params.require(:admin_buy).permit(:quantidade, :valor, :valor, :obs, :truck_id, :seller_id, :product_id)
    end

    def set_admin_sellers
      @admin_sellers =  Seller.all    
    end

    def set_admin_clients
      @admin_clients =  Client.all
    end

    def set_admin_products
      @admin_products =  Product.all
    end

    def set_admin_trucks
      @admin_trucks =  Truck.all
    end

    def set_admin_brands
      @admin_brands =  Brand.all
    end

end

app/views/admin/buys/_form.html.erb
<%= form_for(@admin_buy, html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if @admin_buy.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@admin_buy.errors.count, "error") %> prohibited this admin_buy from being saved:</h4>

      <ul>
      <% @admin_buy.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :quantidade, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :quantidade, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :valor, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :valor, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :valor, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :valor, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :obs, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_area :obs, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :truck, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :truck, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :seller, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :seller, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :product, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :product, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/admin/buys/_search_form.html.erb
<div class="col-sm-12 col-xs-12 hidden--print">

    <form action="/admin/buys/" method="get">

        <div class="row">


            <div class="col-xs-12 drop-margin-top">

                <div class="row">

                    <div class="col-sm-2 col-xs-6">  

                        <label for="ex1">Data Inicial:</label>

                        <input class="form-control text-center" value="<%= @data_inicial %>" name="data_inicial" type="date">   

                    </div>

                    <div class="col-sm-2 col-xs-6">

                        <label for="ex1">Data Final:</label>

                        <input class="form-control text-center" value="<%= @data_final %>" name="data_final" type="date">

                    </div> 
                    
                </div>


                <div class="row">

                    <div class="col-sm-8 col-xs-12 text-center">

                        <div class="col-xs-12"> 
                           <br>
                        </div>

                        
                        <a 
                            href="javascript: admin.setDates(
                                '<%= @general_hoje.strftime("%Y-%m-%d")  %>', 
                                '<%= @general_hoje.strftime("%Y-%m-%d")  %>')" 

                            class="col-xs-3">   
                           
                           Hoje
                        
                        </a>  

                        <a 
                            href="javascript: admin.setDates(
                                '<%= @general_semana_primeiro.strftime("%Y-%m-%d") %>', 
                                '<%= @general_semana_ultimo.strftime("%Y-%m-%d") %>')"   

                            class="col-xs-3"> 
                            
                            Semana atual
                        
                        </a>

                        <a 
                            href="javascript: admin.setDates( 
                                '<%= @general_semana_anterior_primeiro.strftime("%Y-%m-%d") %>', 
                                '<%= @general_semana_anterior_ultimo.strftime("%Y-%m-%d") %>')"   
                                
                            class="col-xs-3">   
                            
                            Semana anterior
                        
                        </a>

                        <a 
                            href="javascript: admin.setDates( 
                                '<%= @general_hoje.strftime("%Y-%m-01")  %>', 
                                '<%= @general_mes_ultimo.strftime("%Y-%m-%d") %>')" 
                            class="col-xs-3">   
                            
                            Mês atual
                        
                        </a>

                    </div>

                    <div class="col-xs-12" >
                        <br />
                    </div>

                </div>
                                

                <div class="row"> 

                    <div class="col-sm-4 col-xs-12">

                        <label for="ex1">Caminhao:</label>

                        <select class="form-control" id="" name="truck_id" placeholder="Código Cupom">  
                            
                            <option value="0">Todos</option>

                            <% @admin_trucks.each do |admin_truck| %>
                                <option

                                    value="<%= admin_truck.id %>"

                                    <% if admin_truck.id.to_s == params[:truck_id] %>  
                                        selected
                                    <% end %>                    

                                > 

                                    <%= admin_truck.placa %>     

                                </option>
                            <% end %>

                            
                        </select> 

                    </div>  


                    <div class="col-sm-4 col-xs-12">

                        <label for="ex1">Vendedor:</label>

                        <select class="form-control" id="" name="seller_id" placeholder="Código Cupom">
                            
                            <option value="0">Todos</option>

                            <% @admin_sellers.each do |admin_seller| %>
                                <option 
                                
                                    <% if admin_seller.id.to_s == params[:seller_id] %>
                                        selected
                                    <% end %>

                                    value="<%= admin_seller.id %>"
                                >       
                                    
                                    <%= admin_seller.nome %>

                                </option>
                            <% end %>
                            
                        </select> 

                    </div>  


                    <div class="col-sm-4 col-xs-12">

                        <label for="ex1">Produto:</label>

                        <select class="form-control" id="" name="product_id" placeholder="Código Cupom">
                            
                            <option value="0">Todos</option>

                            <% @admin_products.each do |admin_product| %>
                                <option 
                                
                                    <% if admin_product.id.to_s == params[:product_id] %>
                                        selected
                                    <% end %>

                                    value="<%= admin_product.id %>"
                                >       
                                    
                                    <%= admin_product.nome %>

                                </option>
                            <% end %>
                            
                        </select> 

                    </div>  



                    <div class="col-sm-4 col-xs-12">

                        <label for="ex1">Marca:</label>

                        <select class="form-control" name="brand_id" >
                            
                            <option value="0">Todos</option>

                            <% @admin_brands.each do |admin_brand| %>
                                <option 
                                
                                    <% if admin_brand.id.to_s == params[:brand_id] %>
                                        selected
                                    <% end %>

                                    value="<%= admin_brand.id %>"
                                >       
                                    
                                    <%= admin_brand.nome %>  

                                </option>
                            <% end %>
                            
                        </select> 

                    </div>  

                    
                </div>


            </div>



            <div class="col-xs-12">
              <hr class="invisible" />
            </div>

            <div class="col-sm-12 col-xs-12">

                <div class="row">

                    <div class="col-sm-6 col-xs-6 drop-margin-top">
                        <button type="submit" class="btn btn-primary drop-btn col-xs-12">
                            Filtrar
                        </button>
                    </div>

                    <div class="col-sm-2 col-xs-6 drop-margin-top">
                    
                    </div>

                </div>
            </div>

            <div class="col-xs-12">
              <hr class="invisible" />
            </div>


        </div>

    </form>

</div>

app/views/admin/buys/index.html.erb
<div class="page-header">  
    <h1>Compras</h1>  
</div>


<%= render 'search_form' %>

<div class="col-xs-12" >

    <div class="table-responsive">  
        <table class="table  table-hover">
            <thead>
                <tr>
                    <th class="col-xs-6" >Quantidade</th>
                    <th class="col-xs-6">Valor</th>
                </tr>
            </thead>
            <tbody>
                <tr>  
                    <td><%= @soma_qtd %></td>
                    <td><%=  number_with_precision( @soma_buys, :precision => 2)  %></td>  
                </tr>
            </tbody>
        </table>
    </div>

</div>



<div class="col-xs-12" >

    <div class="table-responsive">  
        <table class="table table-striped table-bordered table-hover">
            <thead>
                <tr>
                    <th class="col-xs-1" >Código</th>
                    <th>Quantidade</th>
                    <th>Detalhes</th>
                    <th>Caminhão</th>
                    <th>Vendedor</th>
                    <th>Produto</th>
                    <th>Valor</th>  
                    <th></th>    
                </tr>
            </thead>
            <tbody>
                <% @admin_buys.each do |admin_buy| %>
                <tr>  
                    <td><%= admin_buy.id %></td>
                    <td><%= admin_buy.quantidade %></td>

                    <td>
                        Data fonte: <%= date_br( admin_buy.created_at ) %>  <br />                              
                    </td>

                    <td><%= admin_buy.truck.placa %></td>
                    <td><%= admin_buy.seller.nome %></td>
                    <td><%= admin_buy.product.nome %></td>
                    <td class="text-right" >
                        <%= number_with_precision( admin_buy.valor, :precision => 2)  %>                            
                    </td>

                    <td class="text-right" >

                        <a 
                           class="btn btn-danger glyphicon glyphicon-remove" 
                           href="javascript: if ( confirm('Tem certeza?') ) {  
                               window.location.href = '/admin/buy/cancel_buy?buy_id=<%= admin_buy.id %>';     
                           } ">  
                            
                        </a>

                    </td>
                
                </tr>

                <% end %>
            </tbody>
        </table>
    </div>

</div>

app/views/admin/buys/new.html.erb
<div class="page-header">
  <%= link_to admin_buys_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New admin_buy</h1>
</div>

<%= render 'form' %>

app/views/admin/buys/show.html.erb
<div class="page-header">
  <%= link_to admin_buys_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_admin_buy_path(@admin_buy), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show admin_buy</h1>
</div>

<dl class="dl-horizontal">
  <dt>Quantidade:</dt>
  <dd><%= @admin_buy.quantidade %></dd>

  <dt>Valor:</dt>
  <dd><%= @admin_buy.valor %></dd>

  <dt>Valor:</dt>
  <dd><%= @admin_buy.valor %></dd>

  <dt>Obs:</dt>
  <dd><%= @admin_buy.obs %></dd>

  <dt>Truck:</dt>
  <dd><%= @admin_buy.truck %></dd>

  <dt>Seller:</dt>
  <dd><%= @admin_buy.seller %></dd>

  <dt>Product:</dt>
  <dd><%= @admin_buy.product %></dd>

</dl>